/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary-fixed": "var(--color-primary-fixed)",
        "secondary-container": "var(--color-secondary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "primary-container": "var(--color-primary-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "tertiary": "var(--color-tertiary)",
        "background": "var(--color-background)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "on-surface": "var(--color-on-surface)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "primary": "var(--color-primary)",
        "secondary": "var(--color-secondary)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-error-container": "var(--color-on-error-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "on-primary-container": "var(--color-on-primary-container)",
        "tertiary-container": "var(--color-tertiary-container)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-error": "var(--color-on-error)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-background": "var(--color-on-background)",
        "on-secondary": "var(--color-on-secondary)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface": "var(--color-surface)",
        "on-primary": "var(--color-on-primary)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "outline": "var(--color-outline)",
        "error": "var(--color-error)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container": "var(--color-surface-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-tertiary": "var(--color-on-tertiary)",
        "error-container": "var(--color-error-container)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        base: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        sans: ["Be Vietnam Pro", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
