/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d9e3f6",
        "primary-fixed": "#91f8b4",
        "secondary-container": "#64f9bc",
        "on-surface-variant": "#3e4940",
        "tertiary-fixed-dim": "#ffb2b6",
        "primary-container": "#10854d",
        "primary-fixed-dim": "#75db9a",
        "tertiary": "#9b3b46",
        "background": "#f8f9ff",
        "outline-variant": "#bdcabe",
        "surface-dim": "#d0dbed",
        "on-surface": "#121c2a",
        "on-secondary-container": "#00714e",
        "secondary-fixed": "#68fcbf",
        "primary": "#006a3b",
        "secondary": "#006c4b",
        "on-secondary-fixed-variant": "#005137",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#002114",
        "surface-tint": "#006d3d",
        "on-primary-container": "#f3fff2",
        "tertiary-container": "#ba535d",
        "surface-variant": "#d9e3f6",
        "surface-container-high": "#dee9fc",
        "on-tertiary-container": "#fffbfa",
        "on-tertiary-fixed": "#40000d",
        "on-tertiary-fixed-variant": "#802733",
        "inverse-primary": "#75db9a",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#00522c",
        "on-background": "#121c2a",
        "on-secondary": "#ffffff",
        "inverse-surface": "#27313f",
        "surface-container-low": "#eff4ff",
        "surface": "#f8f9ff",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdadb",
        "outline": "#6e7a70",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#00210f",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#e6eeff",
        "secondary-fixed-dim": "#45dfa4",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        base: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        sans: ["Be Vietnam Pro", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
